# Generated by Django 5.1.3 on 2024-12-19 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='payment',
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app1.booking'),
        ),
    ]
